In [ ]:
import pandas as pd

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
df = pd.read_csv("A.csv")

In [ ]:
df.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  1999-11-18  32.546494  35.765381  28.612303  31.473534  27.068665  62546300
1  1999-11-19  30.713520  30.758226  28.478184  28.880543  24.838577  15234100
2  1999-11-22  29.551144  31.473534  28.657009  31.473534  27.068665   6577800
3  1999-11-23  30.400572  31.205294  28.612303  28.612303  24.607880   5975600
4  1999-11-24  28.701717  29.998211  28.612303  29.372318  25.261524   4843200

In [ ]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df['Return_1d'] = df['Adj Close'].pct_change()
df['MA_5'] = df['Adj Close'].rolling(window=5).mean()
df['MA_10'] = df['Adj Close'].rolling(window=10).mean()
df['Volume_Change'] = df['Volume'].pct_change()
df['MA_Ratio'] = df['MA_5'] / df['MA_10']

In [ ]:

# Label: 1 nếu tăng, 0 nếu giảm hoặc bằng
df['Target'] = (df['Adj Close'].shift(-1) > df['Adj Close']).astype(int)
df.head(20)

,Date,Open,High,Low,Close,Adj Close,Volume,Return_1d,MA_5,MA_10,Volume_Change,MA_Ratio,Target
0,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300,NaN,NaN,NaN,NaN,NaN,0
1,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100,-0.082386,NaN,NaN,-0.756435,NaN,1
2,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800,0.089783,NaN,NaN,-0.568219,NaN,0
3,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600,-0.090909,NaN,NaN,-0.091550,NaN,1
4,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200,0.026562,25.769062,NaN,-0.189504,NaN,1
5,1999-11-26,29.238197,29.685265,29.148785,29.461731,25.338428,1729400,0.003044,25.423015,NaN,-0.642922,NaN,1
6,1999-11-29,29.327610,30.355865,29.014664,30.132332,25.915169,4074700,0.022761,25.638333,NaN,1.356135,NaN,1
7,1999-11-30,30.042919,30.713520,29.282904,30.177038,25.953619,4310000,0.001484,25.415324,NaN,0.057747,NaN,1
8,1999-12-01,30.177038,31.071173,29.953505,30.713520,26.415012,2957300,0.017778,25.776751,NaN,-0.313852,NaN,1
9,1999-12-02,31.294706,32.188843,30.892345,31.562946,27.145563,3069800,0.027657,26.153558,25.961310,0.038041,1.007405,1
10,1999-12-03,32.144135,32.680614,31.697067,31.831188,27.376266,3041600,0.008499,26.561126,25.992070,-0.009186,1.021893,1
11,1999-12-06,32.367668,33.217094,32.322960,32.725323,28.145258,2250700,0.028090,27.007144,26.322738,-0.260028,1.026001,0
12,1999-12-07,32.725323,32.904148,31.697067,32.367668,27.837664,2215900,-0.010929,27.383953,26.399638,-0.015462,1.037285,0
13,1999-12-08,32.367668,32.635910,32.054722,32.322960,27.799208,1887800,-0.001381,27.660792,26.718771,-0.148066,1.035257,1
14,1999-12-09,32.367668,32.859444,32.367668,32.770027,28.183710,2029000,0.013831,27.868421,27.010990,0.074796,1.031744,0
15,1999-12-10,32.680614,32.859444,32.010014,32.010014,27.530067,1664700,-0.023192,27.899181,27.230154,-0.179547,1.024569,1
16,1999-12-13,32.546494,33.082977,31.741774,32.546494,27.991461,4020500,0.016760,27.868422,27.437783,1.415150,1.015695,0
17,1999-12-14,32.457081,32.457081,30.087626,30.758226,26.453466,2328900,-0.054945,27.591582,27.487768,-0.420744,1.003777,0
18,1999-12-15,30.042919,30.266453,29.327610,29.819386,25.646021,2917700,-0.030523,27.160945,27.410868,0.252823,0.990882,1
19,1999-12-16,30.042919,33.798283,30.042919,33.798283,29.068048,2583900,0.133433,27.337813,27.603117,-0.114405,0.990389,0

In [ ]:
df = df.dropna()
df.head(20)

,Date,Open,High,Low,Close,Adj Close,Volume,Return_1d,MA_5,MA_10,Volume_Change,MA_Ratio,Target
9,1999-12-02,31.294706,32.188843,30.892345,31.562946,27.145563,3069800,0.027657,26.153558,25.961310,0.038041,1.007405,1
10,1999-12-03,32.144135,32.680614,31.697067,31.831188,27.376266,3041600,0.008499,26.561126,25.992070,-0.009186,1.021893,1
11,1999-12-06,32.367668,33.217094,32.322960,32.725323,28.145258,2250700,0.028090,27.007144,26.322738,-0.260028,1.026001,0
12,1999-12-07,32.725323,32.904148,31.697067,32.367668,27.837664,2215900,-0.010929,27.383953,26.399638,-0.015462,1.037285,0
13,1999-12-08,32.367668,32.635910,32.054722,32.322960,27.799208,1887800,-0.001381,27.660792,26.718771,-0.148066,1.035257,1
14,1999-12-09,32.367668,32.859444,32.367668,32.770027,28.183710,2029000,0.013831,27.868421,27.010990,0.074796,1.031744,0
15,1999-12-10,32.680614,32.859444,32.010014,32.010014,27.530067,1664700,-0.023192,27.899181,27.230154,-0.179547,1.024569,1
16,1999-12-13,32.546494,33.082977,31.741774,32.546494,27.991461,4020500,0.016760,27.868422,27.437783,1.415150,1.015695,0
17,1999-12-14,32.457081,32.457081,30.087626,30.758226,26.453466,2328900,-0.054945,27.591582,27.487768,-0.420744,1.003777,0
18,1999-12-15,30.042919,30.266453,29.327610,29.819386,25.646021,2917700,-0.030523,27.160945,27.410868,0.252823,0.990882,1
19,1999-12-16,30.042919,33.798283,30.042919,33.798283,29.068048,2583900,0.133433,27.337813,27.603117,-0.114405,0.990389,0
20,1999-12-17,33.172390,33.708870,32.501789,32.859444,28.260609,3708000,-0.027778,27.483921,27.691551,0.435040,0.992502,1
21,1999-12-20,33.082977,33.574749,32.993561,33.530045,28.837358,1196800,0.020408,27.653101,27.760761,-0.677238,0.996122,0
22,1999-12-21,33.395924,33.395924,32.904148,33.351215,28.683558,2259400,-0.005333,28.099119,27.845351,0.887868,1.009113,1
23,1999-12-22,33.351215,34.021816,33.127682,34.021816,29.260303,1905700,0.020107,28.821975,27.991460,-0.156546,1.029670,1
24,1999-12-23,33.977112,35.765381,33.932404,35.586552,30.606049,2159400,0.045992,29.129575,28.233694,0.133127,1.031731,1
25,1999-12-27,35.720673,38.045422,35.452431,37.777184,32.490093,2029600,0.061558,29.975472,28.729697,-0.060109,1.043362,1
26,1999-12-28,38.805435,43.991417,38.581902,43.991417,37.834610,3560000,0.164497,31.774923,29.714012,0.754040,1.069358,1
27,1999-12-29,45.064377,56.554005,45.019672,51.502148,44.294170,10518500,0.170732,34.897045,31.498082,1.954635,1.107910,1
28,1999-12-30,54.363377,57.224606,53.111588,56.688126,48.754356,6671100,0.100695,38.795856,33.808916,-0.365775,1.147504,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
features = ['Return_1d', 'MA_5', 'MA_10', 'Volume_Change', 'MA_Ratio']
X = df[features]
y = df['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False, test_size=0.2)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.44574780058651026
[[452   4]
 [563   4]]
              precision    recall  f1-score   support

           0       0.45      0.99      0.61       456
           1       0.50      0.01      0.01       567

    accuracy                           0.45      1023
   macro avg       0.47      0.50      0.31      1023
weighted avg       0.48      0.45      0.28      1023

In [ ]:
import numpy as np

print("Số lượng thật sự 0 (giảm):", np.sum(y_test == 0))
print("Số lượng thật sự 1 (tăng):", np.sum(y_test == 1))
count_0 = (y_pred == 0).sum()
count_1 = (y_pred == 1).sum()

print("Số lượng dự đoán 0:", count_0)
print("Số lượng dự đoán 1:", count_1)

Số lượng thật sự 0 (giảm): 456
Số lượng thật sự 1 (tăng): 567
Số lượng dự đoán 0: 1015
Số lượng dự đoán 1: 8

In [ ]:
# KẾT LUẬN 1: MÔ HÌNH 1 LOGISTIC REGRESSION KHÔNG PHÙ HỢP