In [3]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import math

In [5]:
df = pd.read_csv("clean_data_set/cleaned_stock_data.csv")
df.head(10)

         Date      Open      High       Low      Close    Volume    Return
0  1999-11-19  0.342711  0.340106  0.327058  28.880543  0.237067 -0.082386
1  1999-11-22  0.325436  0.350778  0.329847  31.473534  0.097480  0.089783
2  1999-11-23  0.338060  0.346776  0.329150  28.612303  0.087769 -0.090909
3  1999-11-24  0.312812  0.328768  0.329150  29.372318  0.069509  0.026563
4  1999-11-26  0.320785  0.324099  0.337518  29.461731  0.019297  0.003044
5  1999-11-29  0.322114  0.334103  0.335426  30.132332  0.057117  0.022762
6  1999-11-30  0.332745  0.339439  0.339610  30.177038  0.060911  0.001484
7  1999-12-01  0.334738  0.344775  0.350071  30.713520  0.039098  0.017778
8  1999-12-02  0.351349  0.361450  0.364715  31.562946  0.040912  0.027656
9  1999-12-03  0.363973  0.368786  0.377267  31.831188  0.040457  0.008499

In [10]:
df.isna().sum()
df.count()

Date      4854
Open      4854
High      4854
Low       4854
Close     4854
Volume    4854
Return    4854
dtype: int64

In [7]:
X = df[['Open', 'High', 'Low', 'Volume', 'Return']]
y = df['Close']

In [9]:
X.count()

Open      4854
High      4854
Low       4854
Volume    4854
Return    4854
dtype: int64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [12]:
models = {
    "LinearRegression": LinearRegression(),
    "RandomForest": RandomForestRegressor(n_estimators=100, random_state=42),
    "SVR": SVR(kernel='rbf')
}

In [13]:
models["LinearRegression"].fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = models["LinearRegression"].predict(X_test)
print(y_pred)

[39.33126027 39.64366696 39.47337704 39.96599157 39.62116619 39.92952901
 39.59066709 39.89250924 39.95438842 39.95571795 38.96596014 38.73158545
 39.16505836 39.45717013 39.40962842 39.51087517 38.80760046 39.10324467
 39.38194704 39.87799691 40.42152181 40.16729434 40.29044445 39.98704431
 40.05640552 39.64404706 40.13962406 40.12549505 39.42397983 39.18839367
 40.11129999 40.47215027 40.73563678 40.92800341 40.84205852 40.89569945
 40.96039295 40.18791838 39.83680528 40.52598711 39.45000605 38.491065
 38.571638   38.50999168 38.65460652 39.85145587 38.41137005 37.72744821
 36.51657908 34.78306171 35.03866142 35.23525329 36.49673877 36.37408512
 36.15973636 34.73428436 35.31538219 35.93190777 35.13162363 36.11223343
 35.89356222 35.84245125 35.73724614 35.57181022 36.06406135 36.62654829
 36.62649079 35.7998561  35.66687022 35.00820819 34.99018281 34.27900494
 34.501649   33.49889101 33.811901   34.15580608 33.77030556 34.28681418
 35.26736151 34.71982504 35.62698971 35.88395113 36.19695726 35.96791062
 35.86055851 35.19284985 35.3733664  35.7381565  36.05064827 36.34038163
 36.02458738 36.63507971 36.9710199  36.83188469 36.83168659 37.31338287
 37.57806605 37.95187882 38.45366593 38.30074595 38.22922251 38.19706588
 38.21818961 37.66251402 37.94165306 37.81695559 37.51604242 36.88725365
 37.22983554 37.94694528 39.1231764  38.79508529 39.09250116 39.79622782
 40.42971629 41.19610685 41.88211506 41.75736388 41.3808757  40.7537734
 40.20735701 40.9474204  40.72744065 40.98113167 41.34360199 41.24409789
 40.13500167 40.22757065 40.94048707 41.24488543 40.99355921 40.23201069
 40.97661547 41.09112796 41.71249499 42.07730232 41.68132307 42.32303644
 42.12156146 42.0213888  40.49886911 40.59400248 40.62996455 39.00549557
 38.9756066  37.87996039 38.06537742 37.13899705 37.42384877 37.08194966
 37.285621   36.93679041 37.30690504 38.00261248 37.74964985 37.57863424
 37.28465537 36.28659936 37.43532216 37.511753   37.17023172 36.71598229
 37.48576451 36.12030958 34.70452503 35.28356473 36.36215853 35.22692524
 36.03987137 36.95401621 36.92119408 37.35095214 37.34150905 38.11994767
 37.26227821 37.14332066 37.28162611 37.66068015 37.45386102 38.49390973
 39.01048627 39.03720487 39.38216363 39.42243192 38.23699341 38.15224681
 38.01269256 39.11660139 38.70644559 38.22467352 38.81564167 39.05374705
 40.17958349 39.75023931 39.83950839 39.55194026 39.17281702 39.43584833
 39.86648647 40.19778995 39.79264138 40.12150456 40.05969851 39.36512832
 39.99591644 39.49280866 39.69996863 39.60458376 39.68001076 40.61362044
 40.80545515 40.8185951  41.18546348 41.52490134 41.531858   41.83516474
 41.68295124 41.66569877 41.44740376 41.45122692 41.4099254  40.52869999
 41.6364935  41.09490674 40.68041603 40.88190317 41.33679756 41.52685691
 41.8278702  42.85885958 42.74169401 42.67110626 42.87115769 44.52911302
 44.31417508 44.5185961  45.02208527 44.65329474 45.11850588 45.48532151
 45.35056423 45.66625983 45.79231487 45.78598397 45.99300005 45.42466944
 45.9195604  45.75252766 46.05471461 46.03461233 45.30952648 45.12038154
 44.76699538 45.14760381 45.15262591 45.0488684  46.17252445 45.99179443
 46.20107251 46.63137974 44.10350258 42.32714727 42.73735952 43.68533417
 44.17041405 44.64472852 43.77029601 44.14400832 44.44588853 45.45464756
 45.53302719 46.4131777  46.53315169 46.87841355 46.67372109 46.62713926
 46.78149285 47.00797592 46.70390287 46.5543484  46.07459638 46.52324548
 47.15989184 47.46887761 47.92572206 47.75436668 47.15853561 47.00541712
 46.95686287 47.47140368 47.31702898 47.474343   47.36793161 47.97036297
 47.93947233 48.45844478 48.31167947 48.27816304 46.41912853 47.46540786
 47.59918199 47.95675805 46.9114612  47.18525    47.43826753 47.6803893
 47.30772825 46.93721577 47.00855855 47.11021685 46.90834895 47.01559578
 47.03064793 45.16015438 45.4215259  44.78091881 44.79388921 45.43722051
 44.86882603 45.26770283 45.71514325 45.82720912 46.61325075 46.62249739
 46.45067999 46.46540161 46.9477602  46.49147192 46.98907076 47.08769578
 46.9116822  47.18289701 47.21191117 47.21825281 47.96585434 45.76278831
 45.53743041 45.05409273 45.32954167 45.28989136 45.54082712 45.92066329
 45.9162924  45.35685234 45.80476878 43.7772952  43.53758176 43.70583916
 43.49812378 43.52299775 43.57730345 43.45081415 43.7193036  44.57749821
 45.65873726 45.66812893 45.28467466 47.0776805  46.37415769 45.58818085
 45.50711527 47.2655959  45.72478978 45.37711734 44.84536419 44.24204345
 44.45564472 44.87254637 43.83160112 44.3400438  44.23236655 43.22077605
 43.91762479 44.58622605 44.58517955 44.56428875 45.50150496 46.20041455
 46.47604078 46.43650034 46.34308466 46.47821105 46.19565925 45.69227472
 46.0822823  46.05232492 45.96507247 46.11245602 46.56411673 45.98436708
 45.80490613 45.53973356 46.46295297 47.22745742 46.53530391 47.70350597
 48.30974875 48.12080801 49.04108569 48.19302202 48.65446353 48.41667082
 48.25886003 47.64346703 47.61335591 47.47036058 47.57057111 48.13658507
 48.0626564  48.69462901 47.68003542 48.90144107 49.36461608 48.63964751
 49.37406786 49.16365943 49.58651086 49.73336149 50.54870229 50.21885602
 50.67372272 50.392237   51.37981466 50.8424353  51.33223671 51.38607942
 51.48658868 51.39761117 51.66256845 51.67023066 51.36293793 52.1139421
 51.51382351 51.72156758 51.35732726 51.16507151 51.27547212 51.33019618
 52.06528003 52.27729519 52.03981243 54.30452912 53.30088182 53.29141381
 53.28733822 52.98264245 53.18688095 53.30535121 53.23873327 52.97127821
 53.38775122 53.00325152 53.187406   52.9392338  53.01922611 52.67577761
 53.02952833 52.80012547 52.78347003 52.96772709 52.61818655 52.67700134
 52.51938751 53.32600871 53.11418464 53.12640524 53.02086264 53.07383549
 54.42943103 54.90611774 55.07798439 55.29723432 54.96573827 55.79756372
 55.70721013 56.02142847 56.5710812  56.73061786 56.23876353 56.68735586
 56.32648669 56.05999206 56.16315106 56.52497875 57.12908922 55.9422634
 55.93784926 56.10677305 56.05050485 58.99209515 58.7962481  59.22743819
 59.42886612 60.13253598 60.30356362 60.39183099 60.989005   60.45924589
 60.32685543 60.44552959 60.01812042 59.51269603 58.60650227 59.36202278
 59.37219162 58.97250317 59.56870609 60.37416395 60.58363944 59.95775038
 60.34113559 59.76861099 59.40384582 59.17302447 59.54337466 58.89239032
 59.30271322 59.50701908 59.79736858 59.32740463 59.77902417 59.79282613
 59.72381275 60.72770964 60.93845595 61.30840284 61.60972367 61.13489525
 61.42783298 61.03568765 61.30568796 61.42179047 60.73618111 59.84652473
 59.94898978 59.92392796 60.10416139 60.05132776 59.91375269 60.22335442
 60.29143433 60.59796303 60.39447851 59.65657925 58.57303577 59.40639179
 59.80146537 59.38264898 61.6700552  61.09180847 61.08712648 61.62622364
 62.70599099 63.02274775 62.68313797 62.86057885 63.36266686 63.39196546
 63.75810369 64.5292306  64.57832657 64.15326978 64.41246083 64.89664987
 65.24955017 66.00175091 66.10092242 65.69151603 65.57472261 65.93092909
 65.95957486 66.20254629 65.96126124 65.84864435 65.99412838 64.85485645
 64.2470986  64.38602043 64.24656595 63.99814752 64.78553535 65.53133887
 65.66278492 65.68704913 66.16026761 66.36027582 66.47862893 66.62220097
 67.25634741 67.19786125 66.99784466 66.13088006 66.31613485 66.55443594
 67.34157073 67.21495839 67.18645645 67.71543533 67.51462457 67.67831944
 67.36220549 67.91249248 68.09476383 68.08063135 68.41137026 68.08882724
 68.32417194 67.99775966 67.21648422 66.98786972 66.93380936 67.45295631
 67.17525953 68.51070744 68.71235146 69.74681623 68.96378748 68.59669835
 69.19414388 69.33002046 70.43976367 69.18754282 68.89934388 68.35902753
 67.03648304 66.34387861 65.91818292 66.49740844 67.18133963 66.95392585
 66.75570782 67.06264916 66.70124918 67.42782312 67.99909723 67.70137186
 67.54333829 67.57246396 67.09684027 67.20176368 67.31422332 67.18642679
 67.11296004 67.70853589 68.95178173 69.14826167 69.69015535 69.98603569
 71.53754992 70.45581778 70.65721607 71.36639585 71.61214311 72.05931112
 71.78599618 69.21516834 67.6135331  68.51847021 65.82798845 66.55920204
 68.52761552 68.06864345 69.12443823 72.71974241 72.1725765  71.09264617
 72.027617   70.87473008 70.54260225 70.42927637 69.54281581 69.16838649
 67.44960981 67.25008105 67.13412795 67.99871352 69.05271212 69.71224441
 70.97542579 70.99914972 70.92652438 70.13287685 70.30539806 69.56332192
 69.56729015 69.77016984 69.60847377 67.92941588 66.44824025 67.73159003
 67.17640996 66.32210107 66.88813031 64.6944087  65.41096191 64.75738501
 65.92422539 64.07719542 65.36048093 66.5199717  66.19989964 67.26666239
 67.17980082 68.01597319 68.40961863 69.64138936 67.99831663 67.64708824
 68.23301769 66.97585155 65.66655386 66.38972496 66.20402997 66.02597101
 66.02059367 66.34701427 65.63893906 66.54134749 67.64367856 67.1274604
 67.9398931  68.65136231 69.30022722 69.66212275 61.85546139 62.16143706
 63.21564706 64.21661131 65.58929863 65.08813182 64.65878304 64.44548749
 63.21658831 61.63016318 62.67968132 62.14297892 63.00581901 63.16100679
 63.47547217 64.37064185 65.42644692 65.892615   66.31876342 66.11585428
 66.19689529 65.93920299 65.54148582 64.76125493 63.52569412 62.85560901
 62.7141582  63.04521024 61.34518289 61.84924146 61.87679005 60.99547458
 62.15482824 61.01011449 61.42972254 61.40910386 62.0816629  63.06997232
 63.44634608 62.93294858 63.63198959 63.49348364 62.75600336 62.77068801
 62.95297879 64.24086134 64.00355164 63.64546751 64.76971542 65.6115586
 66.46625793 65.76425023 64.98394609 65.92590282 65.13583747 65.00505373
 65.35445646 66.12522355 67.49611653 67.6921294  66.91378558 66.20509955
 66.23275752 66.87793466 64.87385282 65.34188208 64.59098188 64.80566056
 65.10351258 65.38966583 65.75577145 65.98086555 66.02473205 66.97657239
 66.8870833  67.32392957 67.34724049 67.11190191 66.9632132  67.26059516
 67.48971055 68.15748265 67.74035104 67.64139888 69.1391586  68.8252437
 69.22906501 68.71933766 69.35661425 70.74377553 70.80944917 69.9410743
 70.43544861 70.46881893 70.45613842 70.68445601 71.27120051 71.38986555
 70.9926583  70.14212368 69.27128891 69.07907664 67.30612022 65.33678105
 66.27920918 65.75136217 67.08636958 66.74693421 65.79787092 64.91674507
 63.99543284 61.89730279 62.03042728 62.24824108 62.19062116 62.25654466
 62.93294418 65.38079971 64.94360941 66.13152463 65.71306003 66.02386681
 67.75946392 67.75819412 67.03897196 64.81411697 64.69516012 63.76015995
 63.96003866 65.16527184 63.11888823 67.24352382 67.99021175 68.07697255
 68.88087071 69.15728227 70.80755763 71.81653746 70.81870507 70.43856372
 69.40199525 71.51576199 72.38772716 71.59623947 69.5150799  68.16695348
 68.12057753 67.06235451 65.09344161 64.34996392 62.837877   64.80386995
 65.53743658 66.1692577  67.19723714 65.57151828 63.12289382 65.48281469
 66.88056308 67.48075717 69.11642642 69.37477448 69.80497093 69.96715748
 70.30095395 70.38833334 70.76241995 71.73405699 70.74991837 71.74329977
 67.82451635 68.89125529 69.14542863 69.43706819 69.23843453 67.96786041
 66.79588489 69.25605469 67.60050016 67.47962329 67.16003018 66.96713272
 67.54612406 67.1187784  68.40783999 69.31363701 69.80094231 70.0776411
 70.84347009 69.45914805 70.19198402 69.97133282 70.24495474 71.68227735
 72.21633036 71.58497402 69.88687723 69.70701279 69.93805292 70.18535895
 69.13019695 68.9804248  69.77849917 68.98960977 69.78253968 69.59731997
 70.1139897  69.05066984 69.56167744 69.45313781 67.97589233 66.04552387
 67.13593932 67.52303961 69.0274011  68.10608795 66.99210867 67.91620691
 65.83793707 71.09500109 70.21633008 71.9038531  71.66610961 71.90222101
 69.91793952 69.57447917 69.57522142 69.62844562 70.94555301 71.6904845
 70.03263724 70.49483989 71.99780363 69.09855049 64.29521076 67.20157548
 63.50231807 68.18183192 68.03829288 65.41303967 68.59755779 63.90765724
 66.97518059 68.99662155 71.94466447 71.47519021 68.83363482]

In [16]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(mae)
print(mse)
print(rmse)
print(r2)

0.20378583231641995
0.09084829235983553
0.301410504727084
0.9993939277041167

In [17]:
# Tạo nhãn (close của ngày mai)
df['Close_next'] = df['Close'].shift(-1)

# Loại bỏ hàng cuối vì không có Close_next
df = df.dropna()

# Feature (ngày hôm nay)
X1 = df[['Open', 'High', 'Low', 'Volume', 'Return', 'Close']]

# Label (giá ngày mai)
y1 = df['Close_next']

In [26]:
df.head(10)

,Date,Open,High,Low,Close,Volume,Return,Close_next
0,1999-11-19,0.342711,0.340106,0.327058,28.880543,0.237067,-0.082386,31.473534
1,1999-11-22,0.325436,0.350778,0.329847,31.473534,0.097480,0.089783,28.612303
2,1999-11-23,0.338060,0.346776,0.329150,28.612303,0.087769,-0.090909,29.372318
3,1999-11-24,0.312812,0.328768,0.329150,29.372318,0.069509,0.026563,29.461731
4,1999-11-26,0.320785,0.324099,0.337518,29.461731,0.019297,0.003044,30.132332
5,1999-11-29,0.322114,0.334103,0.335426,30.132332,0.057117,0.022762,30.177038
6,1999-11-30,0.332745,0.339439,0.339610,30.177038,0.060911,0.001484,30.713520
7,1999-12-01,0.334738,0.344775,0.350071,30.713520,0.039098,0.017778,31.562946
8,1999-12-02,0.351349,0.361450,0.364715,31.562946,0.040912,0.027656,31.831188
9,1999-12-03,0.363973,0.368786,0.377267,31.831188,0.040457,0.008499,32.725323

In [19]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, shuffle=False)

In [30]:
X1_train.count()
X1_test.count()

Open      971
High      971
Low       971
Volume    971
Return    971
Close     971
dtype: int64

In [20]:
models["LinearRegression"].fit(X1_train, y1_train)

LinearRegression()

In [ ]:
y1_pred = models["LinearRegression"].predict(X1_test)
print(y1_pred)

[39.78217425 39.5227799  39.80328228 39.58217352 39.90477644 39.46299348
 39.8179235  39.5659183  40.2204887  40.05372078 40.03177799 38.63311504
 38.51447188 39.29161417 39.59445677 39.38143541 39.80452489 38.67901837
 38.87534561 39.40961026 39.96859682 40.5073927  40.10013121 40.33746353
 39.9267642  40.06562114 39.52667941 40.38758332 40.24176211 39.20734895
 39.65297728 40.45607859 40.38190155 41.00374358 40.94235312 41.00070424
 40.55771103 40.67491405 40.00155426 39.96596702 40.47399207 39.32680308
 38.87568946 38.52738398 38.65837459 38.84603698 38.95233938 38.38070955
 37.44865212 36.11345251 34.68991411 34.13667563 35.58638518 36.6511012
 36.51774756 36.29875033 34.70109057 35.52719325 35.74811134 35.0728731
 36.20748023 35.38966739 35.86867959 35.9880106  35.5025645  36.1583007
 36.5263755  36.35651742 35.7384633  35.65490106 35.05820668 34.93835769
 34.56516906 34.40227708 33.28898933 33.75081689 34.33260971 33.66738537
 34.75602437 35.35066383 34.87730795 35.55152753 36.05423095 36.26306871
 35.99149363 35.60603745 34.97583733 35.59175404 35.77294868 36.2791731
 36.34096045 35.82319749 36.05765515 37.11827724 36.82162854 37.084486
 37.53664804 37.71580077 37.7596664  38.62476955 38.27256277 38.335922
 38.29386745 38.14309555 37.91405611 37.9989703  37.60149381 37.50705002
 36.69479482 37.35571648 38.50032454 39.40960298 38.41068846 39.31362735
 40.08989928 40.73629015 41.37797249 41.9851066  41.81022101 40.92956361
 40.32768787 40.08486544 41.13474939 40.67272564 41.20688843 40.92627831
 41.24508763 40.13837314 40.23830127 40.7921823  41.43624837 40.67765967
 40.0547123  40.82433863 41.22016787 41.76615731 42.14966653 41.74842292
 42.36409223 42.146782   41.78212258 40.65600341 40.52169616 40.74606632
 38.86588433 38.48152673 37.81321281 38.13073008 36.65691446 37.61792253
 37.13864988 37.10960254 37.26617957 37.18182959 37.95817587 37.62348921
 37.45864791 36.97422147 35.96332498 37.69425618 37.69893742 37.05826386
 37.1523956  37.42259389 35.89088814 34.70035244 35.41833605 35.81029555
 35.36157384 36.23885269 37.08610371 37.99241035 37.11864619 37.46775723
 38.03001736 37.09759174 37.52900548 37.61351733 37.56316097 37.33248289
 38.63095447 39.0700804  39.21866179 39.34271046 39.44502207 37.97759393
 38.10617872 37.93142619 39.25310339 39.00842888 38.25710118 39.02104631
 39.28510756 40.2137083  39.60875462 39.89492888 39.41480034 39.44990601
 39.50066411 40.18922465 40.06774598 39.84352888 40.35825765 39.96711844
 39.204332   40.27992683 39.4094867  39.50278912 39.33938613 39.76220999
 40.72891875 40.75436266 40.92425013 41.33505092 41.40082581 41.52217428
 41.95345604 41.77831824 41.6228239  41.25361538 41.57582478 41.15039757
 40.9098244  41.7290846  41.22740092 40.47095683 40.97206988 41.44615054
 41.29872772 42.02550493 42.43139317 42.73069852 42.61824509 42.96687824
 44.26307851 44.28919673 44.58449983 44.87251362 44.53045049 45.03644125
 45.43224974 45.50108026 45.83322813 45.89440075 45.94954567 45.89550193
 45.70844457 45.8720639  45.73908028 46.17257458 46.09793039 45.31256172
 44.85735522 44.9279461  44.90510804 45.40068054 45.35360623 46.16034203
 46.14086916 46.00267689 46.68385988 44.08653177 42.0767649  43.12374447
 43.74455627 44.39495911 44.6057317  43.68039355 44.4980159  44.39847957
 45.50025115 45.36262092 46.54717138 46.3702993  46.77832209 46.62804038
 46.80223984 47.00221246 47.00916279 46.61294404 46.55823061 46.0908262
 46.9672481  47.25252586 47.5103197  48.13282145 47.83413265 47.10189588
 47.08834734 46.77459914 47.50376116 47.17552712 47.45899522 47.49785247
 48.14352323 48.1438647  48.44807315 48.27824749 48.39701773 46.69431262
 47.66505413 47.55904927 47.80951381 46.55098127 47.28062803 47.27521075
 47.60673197 47.06137767 46.95974384 46.97150754 46.95456707 46.94600167
 47.10775359 47.01197669 44.65778826 45.79807366 44.84656657 44.8317752
 45.45292839 44.71834178 44.92392499 45.70574965 46.00855147 46.67759974
 46.61127784 46.56767452 46.70570512 47.17394022 46.3005492  47.09398543
 47.16196893 46.78399365 47.14411598 47.31044609 47.37057792 47.66475993
 45.47829448 45.43106923 45.18170603 45.02263763 45.13679685 45.38751892
 46.04188229 46.03696575 45.56186987 45.83899695 43.24294776 43.3482805
 43.27986018 43.16952675 43.57489711 43.42481883 43.22876422 43.65761346
 44.31173215 45.72687781 45.61395057 45.93332494 47.00926427 46.3165301
 45.13235785 45.3718109  46.05255111 45.90634097 44.90740296 44.9328986
 44.36200194 44.66901213 44.88958228 43.47377375 44.50947007 43.85908182
 43.08463174 44.06668025 44.54478013 44.83819087 45.00599358 45.82885074
 46.32184157 46.10681232 46.38006034 46.0772115  46.56525085 45.78990754
 45.34303754 46.21411057 46.00896839 45.96641468 46.20169083 46.51063562
 45.59395241 45.61769687 45.52676824 46.48539342 47.08401751 46.46600223
 48.04126653 48.12464803 48.04256431 49.30358337 48.46510689 48.68181589
 48.2993726  48.17339435 47.5839012  47.57975954 47.34837477 47.24905664
 48.44168884 48.13293024 48.65401144 47.5461768  48.99354539 49.23226427
 48.89202443 49.38583435 49.27069206 49.64006109 49.95291612 50.47744135
 50.32694791 50.48235074 50.39237689 51.61289849 50.70950232 51.67419219
 51.29321506 51.31584023 51.45332955 51.75298323 51.62898825 51.26280727
 52.04127259 51.28059094 51.99432007 51.18881022 51.20363383 51.39579857
 51.4120897  52.14392124 52.45935654 52.2039212  54.05692513 52.95746068
 53.30348445 53.0978036  52.52369868 53.11111152 53.13272935 52.90972388
 53.26058359 53.42718641 53.0795669  53.31409993 52.8358484  53.2076204
 52.52923797 52.67561882 53.14571633 52.80412865 52.66478698 52.82109319
 52.49041685 52.29505306 53.46001844 52.98361591 53.01898178 53.07952753
 53.24967034 54.44641717 54.77438388 54.77956953 55.43861317 55.01183267
 55.78679839 55.91767634 56.17435502 56.7199373  56.59615414 56.24341656
 56.87903733 56.1660492  56.21128895 56.13690467 56.71840283 56.53728915
 55.60290415 55.80548199 56.10580059 56.01224458 58.40508175 59.24512947
 59.23478396 59.49569312 60.38941944 60.35520536 60.75064745 60.77975397
 60.3281743  60.06735191 60.61578368 60.0557845  59.02206618 58.91284324
 59.25146613 59.31417357 59.18510952 59.48774586 60.57759267 60.26500648
 59.68817085 60.61138317 59.63427091 59.13529524 58.80340901 59.36914369
 58.67660435 59.29022386 59.02139238 59.76776288 59.15994568 59.58107095
 59.85363659 59.74644563 60.70519641 61.14427469 61.49578302 61.51126427
 61.15390327 61.3506228  60.88890064 61.36690679 61.48606947 60.35928353
 59.55425079 59.87731725 60.05790324 59.67313035 59.8923242  60.17054592
 60.36042944 60.03714551 60.88143221 60.02842983 59.59468885 58.42963871
 59.32053999 59.56609936 59.30920449 62.03613166 60.68029716 61.21333109
 61.73680732 62.98853314 62.71882731 62.60745489 62.84634828 63.44851521
 63.49454321 63.90901    64.72802266 64.25649334 64.27177969 64.67085519
 65.11426894 64.94275861 66.10106412 66.08312892 65.33822788 65.66653472
 65.95131693 66.03516673 66.12165193 66.02420107 65.88468709 65.72507588
 64.53213717 63.99081919 64.35349812 63.9017288  64.18322317 64.86540618
 65.09280859 65.84015183 65.65168123 66.37445032 66.51467005 66.54337067
 66.56696912 67.55352555 66.85391058 66.83150954 66.02049605 66.40291567
 66.86254522 67.21116237 66.9153676  67.27202224 67.22689843 67.68010978
 67.94284815 67.40123333 68.00781972 67.95063671 68.09109756 68.34121372
 68.1701368  68.18922135 68.06712868 67.3614351  66.69420372 67.12270347
 67.4456833  67.27031467 68.75920572 68.75956843 69.94597498 69.73644951
 68.59062976 69.35813406 69.28724007 70.58567099 68.3524127  69.1753793
 68.47547447 65.77981559 65.70170169 65.84218898 66.7160432  67.36135494
 66.87785067 67.02661658 66.54601571 66.43748763 67.59040666 67.55733922
 67.68484234 67.28614811 67.47102032 67.29849159 67.20598557 67.27677964
 67.41213065 66.86427051 67.56160137 69.35953945 68.64784313 69.91861715
 70.0229844  71.72863531 70.65179555 70.7226051  71.7343866  71.04268778
 72.02821484 71.02627522 67.74532277 68.46228725 67.95936437 64.5614771
 66.89633419 68.41248997 68.3263686  69.75760876 71.43828045 71.89153722
 70.96663789 71.12397345 70.48633542 70.57711703 70.47851153 68.70084859
 68.40352538 67.14905536 67.51706382 67.50080768 68.07816819 69.78212368
 69.79128354 71.10562028 70.59225651 70.56007714 69.70079627 70.1271602
 69.82780554 69.21062854 69.80818513 69.29261819 67.22752938 65.79464095
 68.18293773 66.71902039 66.22146836 66.81653149 64.02244406 65.37694249
 65.49317188 65.60163595 63.39318365 65.05909986 66.61517274 66.0372228
 67.172312   67.12451971 68.14044948 68.36793056 69.47257144 67.6859667
 67.43516782 68.02064382 66.56346689 65.5946372  66.31885562 66.22907469
 65.5993973  66.25095814 65.82234183 66.30948415 66.98934351 67.33667774
 67.3621762  68.1192521  68.87765051 69.41915811 69.05555475 62.52608642
 61.82019624 63.62970209 64.32713323 65.54592198 64.69026639 64.51877324
 64.00083865 62.9953705  61.7137824  62.6575668  61.78909726 62.7463327
 63.35044465 63.47399893 65.21096698 65.12681499 65.68960344 66.09782841
 66.29686927 66.19016346 66.26066813 66.09050793 64.87243955 63.39961831
 62.67561148 63.02138503 62.64747157 60.97020007 61.9798881  60.89757584
 61.23409837 61.78459268 61.45225764 61.10647914 61.77606375 62.28142753
 63.12281484 63.6551689  62.85134651 63.41586516 63.31647347 62.62892312
 63.02350005 62.9509556  64.10710785 63.80668815 63.68040036 64.76206087
 65.96575949 66.76070693 65.57848084 64.40195448 66.00647125 64.8031499
 65.29182488 65.70063201 66.51183019 67.65359381 67.27868469 66.53932623
 66.14467623 65.80257478 66.73558422 64.50914823 65.49095631 64.51030915
 64.40734417 64.89281201 65.65976219 65.65581134 65.95410005 66.01296659
 66.64127269 66.98088084 67.22830441 67.5428925  67.21743152 66.88297417
 67.33832458 67.36467452 67.8793393  67.56786424 67.88611932 69.33742957
 68.74662422 68.96351874 68.85583807 69.55105485 71.17187037 70.58754028
 69.81359976 70.328774   70.23229123 70.76644932 70.48093541 71.24817533
 71.67388401 70.42342082 70.15404081 69.39143062 69.36145304 66.22489307
 64.57641401 66.13331093 65.53547636 67.46815568 67.1396455  65.49908849
 64.20882516 64.16368807 62.66410484 60.77866686 62.61039557 62.72011311
 61.73511686 63.65004593 64.70229688 65.18484629 65.85340752 65.82737468
 65.92142937 68.29448011 67.70982523 67.17811626 64.24209424 64.20990911
 63.26787337 64.72783786 64.97221181 62.25874393 67.40747002 67.62709883
 68.22209931 69.21602134 69.35840102 71.51119165 71.53165775 71.8791233
 69.95058157 70.4915341  70.84462461 71.58538644 70.91007815 69.16430776
 67.58338453 67.82804798 66.48240652 64.98133788 62.91132583 62.55579048
 65.61465757 66.53797885 65.76069818 67.48564207 65.54637324 62.84952572
 65.46170079 66.84730947 67.74850112 69.23740063 69.89631154 70.39775674
 69.70809624 70.58408606 69.85971077 70.81699154 71.88431201 71.254459
 71.47022254 67.5497276  69.36201709 69.08028858 68.86856254 68.06133651
 67.89265776 67.67998113 68.2433229  66.8217558  67.2840068  66.74107127
 67.04147205 66.88906012 67.89710107 68.24045453 69.13567455 69.42253058
 70.26348079 69.66189219 70.23346401 70.21338355 69.88178847 70.23235074
 71.90139499 71.38794348 71.59388642 70.43569654 69.89027414 69.44239011
 70.06992505 68.38105577 69.04180305 69.8698738  69.57106857 69.82004684
 69.37608926 70.38228514 70.14121979 69.22640252 69.0142804  67.88621284
 65.68779341 67.67590139 67.9760095  69.4981708  68.55334194 66.35509125
 67.55594318 65.40504456 69.07160172 71.06756396 71.65931147 71.00001702
 71.54582447 69.2072568  69.46607118 69.33473457 69.91253094 70.61003965
 70.94485803 70.29142156 70.76540663 70.28188339 68.40504034 63.1100929
 69.098007   63.95605866 70.47087604 69.01071393 65.24313726 66.07579718
 62.69905366 66.88522504 68.75590511 70.60067713 71.38437613]

In [31]:
print(X1_test)

          Open      High       Low    Volume    Return      Close
3882  0.485630  0.485295  0.502724  0.036071 -0.017024  39.840000
3883  0.475227  0.472464  0.495081  0.029497 -0.008032  39.520000
3884  0.474632  0.475150  0.497109  0.014350  0.006832  39.790001
3885  0.477159  0.475000  0.496173  0.015911 -0.004775  39.599998
3886  0.477753  0.478879  0.502412  0.021484  0.007576  39.900002
...        ...       ...       ...       ...       ...        ...
4848  0.879024  0.889152  0.851348  0.039619 -0.046494  63.369999
4849  0.860150  0.898402  0.890499  0.037672  0.057283  67.000000
4850  0.883780  0.952259  0.898455  0.033789  0.029851  69.000000
4851  0.949618  0.973444  0.979098  0.020916  0.027681  70.910004
4852  0.961359  0.967327  0.982530  0.020792  0.010013  71.620003

[971 rows x 6 columns]

In [23]:
mae = mean_absolute_error(y1_test, y1_pred)
mse = mean_squared_error(y1_test, y1_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y1_test, y1_pred)
print(mae)
print(mse)
print(rmse)
print(r2)

0.6258454360864146
0.8840771410204216
0.9402537641617935
0.9941020942862205

In [24]:
pred_df = pd.DataFrame({
        'Date': df.iloc[y1_test.index]['Date'],
        'Actual': y1_test,
        'Predicted': y1_pred
    })

In [25]:
pred_df.to_csv(f"result/HuyenTest.csv", index=False)

In [27]:
pred_df.head(10)

            Date     Actual  Predicted
3882  2015-06-12  39.520000  39.782174
3883  2015-06-15  39.790001  39.522780
3884  2015-06-16  39.599998  39.803282
3885  2015-06-17  39.900002  39.582174
3886  2015-06-18  39.490002  39.904776
3887  2015-06-19  39.810001  39.462993
3888  2015-06-22  39.599998  39.817924
3889  2015-06-23  40.189999  39.565918
3890  2015-06-24  40.049999  40.220489
3891  2015-06-25  40.020000  40.053721